<template>
  <section>
    <div class="container-middle">
      <h1 class="text-30 f-bold title1">Cookies and similar tracking technology</h1>
      <h2 class="text-18 f-bold title1">
        What are Cookies?
      </h2>
      <p class="text-14 text1 mb-15">
        A cookie is a small text file that becomes stored on your computer or mobile device when you view a web page or
        certain types of content-rich e-mails. Cookies remember information. Cookies allow us to provide you with
        relevant information as you use or return to our site. Web beacons allow us to know if a certain page was
        visited, an email was opened, or if ad banners on our website were effective. We use the following types of
        Cookies:
      </p>
      <ul class="text-14 text1 list-ul disc mv-15">
        <li>Necessary Cookies: Required for our website to function correctly.</li>
        <li>Performance Cookies: Tracks web page visits, including frequency, and how individuals browse the site.</li>
        <li>Functional Cookies: Increases the base functionality of our website. For example, allows you to watch a
          video.
        </li>
        <li>Targeting Cookies: Remembers your online behavior (on and off our website). Targeting Cookies may remember
          your IP address, device used, (computer or mobile) device ID, date and time you browse, address of a referring
          website, your pathway through our webpages, as well as your cart and purchase history. We and third parties,
          including advertisers, social media networks, search engines and service providers use targeting Cookies to
          provide you with online behavioral advertising. These are relevant and personalized ads provided to you based
          on your browsing history. Targeting Cookies are also used to analyze and monitor overall website behavior and
          traffic.
        </li>
      </ul>

      <h2 class="text-18 f-bold title1">
        How long are Cookies stored on a computer or device?
      </h2>
      <ul class="text-14 text1 list-ul disc mv-15">
        <li>Persistent Cookies: Persistent Cookies do not expire after you close your browser. They remember your
          information and settings for future visits to our website. For example, your language preference.
        </li>
        <li>Session Cookies: Session Cookies expire after you close your browser. They remember your information and
          settings during your current visit to our website. For example, items in your shopping cart.
        </li>
      </ul>

      <h2 class="text-18 f-bold title1">
        Can I turn off cookies?
      </h2>
      <p class="text-14 text1">(i) Necessary, Performance, and Functional Cookies</p>
      <p class="text-14 text1"><span class="text-underline">Website:</span> You can turn off necessary, performance, and
        functional cookies. However, turning off these cookies may impact our website’s performance and your ability to
        use some of its features. You can turn off these cookies through your web browser. You can learn how to do so by
        following these links:</p>
      <ul class="text-14 text1 list-ul disc mv-15">
        <li><a href="https://support.microsoft.com/en-ca/help/17442/windows-internet-explorer-delete-manage-cookies" class="text-secondary text-underline" target="_blank">Microsoft Internet Explorer</a></li>
        <li><a href="https://support.mozilla.org/en-US/kb/cookies-information-websites-store-on-your-computer?redirectlocale=en-US&redirectslug=Cookies" class="text-secondary text-underline" target="_blank">Mozilla Firefox</a></li>
        <li><a href="https://policies.google.com/technologies/cookies" class="text-secondary text-underline" target="_blank">About All Cookies</a></li>
      </ul>
      <p class="text-14 text1 mb-15"><span class="text-underline">APP:</span> If you have downloaded an Art.com mobile app, you can stop all collection of data generated by the use of the app by uninstalling it.</p>

      <p class="text-14 text1">(ii) Targeting Cookies</p>
      <p class="text-14 text1">
        Online Behavioral Advertising You can choose to turn off targeting Cookies without impacting our website’s function and performance. However, when you turn off targeting Cookies, you may miss certain products or services that may be of interest to you. If you opt out of receiving online behavioral advertising, you will continue to receive advertising, but it will not be based on online behavioral information about you. </p>
    </div>
  </section>
</template>

<script setup lang="ts">
import {pageMeta} from "~/config/pageMeta";

useHead(pageMeta["/cookies-policy"] ?? {});

defineOptions({
  name: 'PrivacyPolicy'
})
</script>

<style scoped lang="scss">
.title1 {
  line-height: 35px;
  margin-bottom: 15px;
}

.text1 {
  line-height: 25px;
  text-align: justify;
}

.list-ul {
  padding-left: 1.5rem; /* 视情况添加 */
  &.disc li {
    list-style-type: disc !important;
  }

  &.decimal li {
    list-style-type: decimal !important;
  }

  li {
    list-style-position: outside !important; /* 或 inside，根据你设计需求 */
  }
}

</style>